### ISSUE TITLE
Viu incompatible with python 3.8

### ISSUE THREAD

**Issue by CaspianA1** [atanunq/viu#33]
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

**Comment by jugmac00** [comment]
Uhm, isn't `viu` a Rust application?

**Comment by atanunq** [comment]
Yes, could you please elaborate?

**Comment by CaspianA1** [comment]
I'm calling it from Python and I recently installed Python 3.8, and from there it stopped working. This is what is looks like when I use viu in xterm:


********-MacBook-Air:OTF_ASCII ***********$ viu sprite_00.png 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/viu", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/viu/viu.py", line 184, in main
    Viu(file_path.read_text()).main()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/pathlib.py", line 1228, in read_text
    return f.read()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
********-MacBook-Air:OTF_ASCII *********$ 

I am not sure why it is giving me these errors, but it mentions python though.

**Comment by atanunq** [comment]
Thanks for reporting! Debugging on Mac has been on my todo list for a while. I will try to get my hands on one soon.

**Comment by CaspianA1** [comment]
Thanks! And also another problem with Mac is that it doesn’t display colors accurately - just wanted to let you know.

Caspian
